version: '3.5'

services:
  app:
    image: docker.pkg.github.com/lzfw/php-apache2-basic-auth-manager/app:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./config.yml:/var/www/config.yml
      - passwords:/var/htsecrets/
    ports:
      - 80:80

volumes:
  passwords:

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

